on:
  push:
    branches:
      - main
jobs:
  ec2deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2서버에 접속하기
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/security-server
            git pull origin main
            chmod 744 gradlew
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./scurity.log 2>&1 &