# workflow이름 - 하나의 yaml파일을 하나의 workflow임.
name: EC2에 자동배포하기

# Event설정하기
# main이라는 브랜치에 push발생하면 아래 workflow실행한다.
on:
  push:
    branches:
      - main

# 하나의 workflow는 1개 이상의 Job으로 구성된다.
# 하나의 Job은 여러 Step으로 구성할 수 있다.
jobs:
  ec2deploy:
    runs-on: ubuntu-latest

    steps: #특정 작업을 수행하는 가장 작은 단위
      - name: EC2서버에 접속하기 #step에 붙이는 이름
        uses: appleboy/ssh-action@v1 #실행시킬 리눅스 명령어 작성
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/schedule-backend
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./schedule.log 2>&1 &